[package]
name = "camera_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canonical-error = "0.1.0"
asi_camera2 = { version = "0.1.0", path = "../asi_camera2" }
