[package]
name = "libcamera-meta"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
git2 = "0.19.0"
indoc = "2.0.3"
prettyplease = "0.2.17"
semver = "1.0.22"
syn = "2.0.58"
yaml-rust = "0.4"
